apiVersion: v1
kind: Service
metadata:
  name: laravel-nginx-service
spec:
  selector:
    app: laravel
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Or NodePort, depending on your cluster setup

