apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-nginx
  labels:
    app: laravel
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
      tier: frontend
  template:
    metadata:
      labels:
        app: laravel
        tier: frontend
    spec:
      containers:
      - name: laravel-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        - name: nfs-storage
          mountPath: /var/www/html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: pvc-nfs-laravel

