apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-laravel
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.20.30.50
    path: "/mnt/code"

